### ISSUE TITLE
[Exercise 1.1] Self-Play

### ISSUE THREAD

**Issue by lijiyao919** [vojtamolda/reinforcement-learning-an-introduction#14]
In the formal proof, I think the words should be "**_Exploration_** makes the sub-optimal agents adjust its policy causing the contradiction with the convergence to a sub-optimal behavior"

**Comment by vojtamolda** [comment]
Hello @lijiyao919 and thanks for raising the issue here.

I wouldn't exactly call the solution in this repo a formal proof. It's an equivalent of hand-wavy discussion 😄  In my view, the right word here actually is exploitation. It pertains to the min-max nature of the simultaneous optimization process happening between two agents.

Exploitation happens whenever one policy has a weak spot and performs a sub-optimal action. In that case the other agent can take advantage, i.e. exploit, this weakness. This in turn forces the other party to learn about the non ideal value function it has been using to make its decisions.

**Comment by lijiyao919** [comment]
Thanks:)
