### ISSUE TITLE
Truncated typed answers in all exercises in chapters 3, 4, 6 and 9

### ISSUE THREAD

**Issue by Jonathan2021** [vojtamolda/reinforcement-learning-an-introduction#6]
In all exercise solutions from chapter 6, answers typed with the keyboard are truncated at the end (might be the same for subsequent chapters, I didn't check).

**Comment by vojtamolda** [comment]
I checked and the problem also appears in chapters 3, 4, 6, 7 and 9.

The root cause looks like an export bug in the [Notability](https://apps.apple.com/us/app/notability/id360593530) app i use to edit the notes.. The exported note uses a larger default font which makes the text overflow from it's container.  Later version don't seem to suffer from the problem so the fix is simple - reexport the notes again.

**Comment by vojtamolda** [comment]
All the overflowing text boxes are fixed now.
